cs111/django/urls.py
from django.urls import path

from . import views

app_name = 'cs111'

urlpatterns = [
    path('', views.index, name='index'),
    path('lectures/', views.LecturesView.as_view(), name='lectures'),
    path('labs/', views.LabsView.as_view(), name='labs'),
    path('resources/', views.resources, name='resources'),
    path('grades/', views.grades, name='grades'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('cs111.django.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/profile/', include('django_ssh.urls', namespace='ssh')),
]

website/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CS 111{% endblock %}</title>
    <link rel="icon"  type="image/png" href="{% static "favicon.png" %}" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Overpass&family=Overpass+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="{% static "css/cs111.css" %}">
    <script>
      document.addEventListener('DOMContentLoaded', () => {
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
        if ($navbarBurgers.length > 0) {
          $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {
              const target = el.dataset.target;
              const $target = document.getElementById(target);
              el.classList.toggle('is-active');
              $target.classList.toggle('is-active');
            });
          });
        }
      });
    </script>
  </head>
  <body>
    <nav class="navbar is-primary" aria-label="main navigation">
      <div class="navbar-brand">
	<a class="navbar-item" href="{% url 'cs111:index' %}">
	  <strong>CS 111</strong>
	</a>

	<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="cs111_navbar">
	  <span aria-hidden="true"></span>
	  <span aria-hidden="true"></span>
	  <span aria-hidden="true"></span>
	</a>
      </div>
      <div id="cs111_navbar" class="navbar-menu">
	<div class="navbar-start">
	  <a class="navbar-item" href="{% url 'cs111:lectures' %}">
	    Discussions
	  </a>
	  <a class="navbar-item" href="{% url 'cs111:labs' %}">
	    Labs
	  </a>
	  <a class="navbar-item" href="{% url 'cs111:resources' %}">
	    Resources
	  </a>
          {% if user.is_authenticated %}
	  <a class="navbar-item" href="{% url 'cs111:grades' %}">
	    Grades
	  </a>
	  {% endif %}
	</div>
	<div class="navbar-end">
          {% if user.is_authenticated %}
	  <a class="navbar-item is-family-monospace" href="{% url 'ssh:index' %}">
	    {{ user.username }}
	  </a>
          {% endif %}
	  <div class="navbar-item">
            <div class="buttons">
              {% if user.is_authenticated %}
              <a class="button is-info" href="{% url 'logout' %}">
                Logout
              </a>
              {% else %}
              <a class="button is-light" href="{% url 'login' %}">
                Login
              </a>
              {% endif %}
            </div>
          </div>
	</div>
      </div>
    </nav>
    <section class="section">
      <div class="container">
	{% block content %}{% endblock %}
      </div>
    </section>
  </body>
</html>